# autogenerated by txs
#include:latex-document
#include:tex
\bob#S
\grenzop{arg1}{arg2}{arg3}#S
\langrechtspfeil{arg1}{arg2}#S
\seclen
\skipsection#S
\subseclen
\thissemester#S
\thisshorttitle#S
\thistitle#S
